builddemo: builddemo.o add.o sub.o
	gcc -o builddemo builddemo.c add.c sub.c



builddemo.o: builddemo.c
	gcc -c -o builddemo.o builddemo.c



add.o: add.c
	gcc -c -o add.o add.c



sub.o: sub.c
	gcc -c -o sub.o sub.c
